name: simple-haskell-minifier
version: 0.1.1.0
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/simple-haskell-minifier
language: GHC2021

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -Wno-partial-type-signatures
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wno-missing-methods

default-extensions:
  - OverloadedStrings
  - ImportQualifiedPost
  - LambdaCase
  - DerivingStrategies
  - DuplicateRecordFields
  - OverloadedRecordDot
  - BlockArguments
  - StrictData
  - MultiWayIf

dependencies:
  - base < 5
  - bytestring
  - containers
  - ghc-lib-parser

  - directory
  - pretty-simple
  - tasty
  - tasty-golden
  - text

executables:
  simple-haskell-minifier:
    main: Minifier
    source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: [test, src]
    ghc-options: -threaded -rtsopts -with-rtsopts=-T
